spring:
  application:
    name: tttare-eureka-service
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8761
---
spring:
  # profile=peer1
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    # when profile=peer1, hostname=peer1
    hostname: peer1
  client:
    #是否将自己注册到eureka server 中
    registerWithEureka: false
    #是否同步其他eureka server注册信息
    fetchRegistry: true
    service-url:
      # register self to peer2
      defaultZone: http://peer2:8762/eureka
---
spring:
  # profile=peer2
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    # when profile=peer2, hostname=peer2
    hostname: peer2
  client:
    registerWithEureka: false
    fetchRegistry: true
    service-url:
      # register self to peer1
      defaultZone: http://peer1:8761/eureka